name: sistem_informasi_smanda
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  http: 0.13.5
  introduction_screen: 3.0.2
  google_fonts: ^3.0.1
  lottie: 2.0.0
  convex_bottom_bar: 3.1.0+1
  animated_splash_screen: 1.3.0
  google_nav_bar: 5.0.6
  smooth_page_indicator: 1.0.0+2
  flutter_heatmap_calendar: 1.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

